[package]
name = "authserver"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.18.0", features = ["derive"] }
tokio = { version="1", features=["full"] }
client = { path="../client" }
